import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/common/Header";
import Providers from "@/components/common/Providers";
import MenuDrawer from "@/components/common/MenuDrawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Providers>
          <div className="relative overflow-x-hidden h-min-screen">
            <Header />
            <main>
              <div className="w-full max-w-[1100px] mt-[50px] mx-auto">
                {children}
              </div>
            </main>
            <MenuDrawer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
